include: package:lint/strict.yaml

linter:
  rules:

analyzer:
  exclude:
    - "**/*.g.dart"
    - packages/**
    - test/**
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
  rules:
    - avoid-dynamic
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - prefer-conditional-expressions
    - prefer-match-file-name
    - prefer-moving-to-variable
    - prefer-trailing-comma